---
title: "First Knit"
author: "Your Name"
date: "Date, 2019"
output: 
  html_document:
    number_sections: true
    toc: true
---

### `r as.character(Sys.Date())`

```

```

```
```

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. Half the points in this assignment depend on your picture and name being correct!!  Be sure to put your photo in the AAA_Owner_Info folder and call it My_photo.jpg after first renaming the current one to Koala.jpg . 

##Where are you now?  
What row are you in, front,middle or back?  Do you usually choose a similiar row in other classes? What is the computer number where you are sitting?  How on a scale of 1 to 10 (1=low, 10=high) How you feel about periodic seat re-assignment, say how and why. Teams, have you ever worked on one in a class setting?  

###my answer     
  
  I am sitting in the middle of the class, close to the wall.
  
  I usually sit near the front, but the seats next to a power outlet were taken
  
  10 , I like periodic seat re-assignment because you get to meet more people.
  
  I worked in group projects before and I usually enjoy collaborating. 
  
  I haven't worked in a team outside of school setting.


##Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want me to call you something else - what would that be? 

###my answer     
  
  My name is Jaime Duran Jr.  I like to be called J-Dawg online like gamer profiles and such. In school and professional settings I go by Jaime, pronounce "high meh".
 




##Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

###my answer     
  
   
 I want to do public service and work in a non profit setting. I am interested in helping the Homeless and studying land use policies. I am currently studying to earn my Masters in Public Administration. 




##Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

###my answer     
  
   I go to Mexico and visit my family regularly. Maybe once or twice in a year. I would like to go to Mexico, and visit places where I haven't been to like the jungles and pyramids that are far from where my family lives. 
  




##Why are you taking MMGMT 6770?  
What grade do you need to attain in class to not upset your future plans, What is your plan?
 

###my answer     
  
   I would like to get an A plus, and I will try my best to do well in this class because I value becoming familiar with the R Studio user interface. I believe this will help me make more informed and data driven decisions throughout my career, wehrever I end up being employed. 
 





##Homework Help and Getting around?  
On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  Do you have a computer you can use at home? If so, what kind is it (windows, Apple, Linux)? Do you have internet access at home?  
How do you get to class? Are there issues that limit when you can be at the college?Where and when did you attend high school?  Do you currently have a job?

###my answer   
   6. 
   I know enough about basic hardware concepts like the function of RAM, and I know about some software concepts like the webscraping functions of Python. I know Javascript helps visualize data. But I don't know how to write R, Python, and Java code because I haven't taken the time to train myself. 
   
## critique of the AI in business article 

I thought the article was insightful if you are interested in theoretical approaches to scaling the use of artificial intelligence beyond small pilot tests and implement AI adoption thoroughout a large organization. 

The most valuable insight I took away from the article was the realization that AI tools are more likely to supplement worker's roles in an organization, rather than replace the workers altogether and still yield cost cutting benefits to the organization's that invest in user friendly, slow paced, AI adoption policies.Workers will be expected to be technologically proficient. 

The author correctly emphasized the need to onboard frontline staff and mid level managers into AI adoption strategies; reducing conflict through rhetoric that reduces the adversarial nature between laborers and machines that make human labor and intuition less inherently integrated into processes that fulfill organizational roles and functions. 

However, the rhetorical 'call to arms' that the article suggests will be futile or of little help when the organization reaches the phase where, in the authors words, ' processes become standardized' and experts can depart from central hubs and 'reside in spokes more effectively'. It is more likely that as AI adoption matures and workflow redesigns are relatively tested and proven stable, that the organization will decrease its resources, and reduce spending on technical personnel by promoting agile technicians and reducing their support staff. At the point where organizational downsizing begins reducing personnel spending in the AI or tech department, other business units in the organization will likely percieve their own roles and position under threat. 



